pdf-backend: include <goo/gfile.h> instead of <goo/gtypes.h>.
<goo/gfile.h> was only needed for the Goffset definition.
This definition has been moved to <goo/gfile.h>:

https://cgit.freedesktop.org/poppler/poppler/commit/?id=27954f7d44275d4fc458da680bba89ab749d3c07

Fixes:

    pdf-backend.hh:43:24: fatal error: goo/gtypes.h: No such file or directory

with Poppler > 0.72.